pane:
  name: workspaces
  widgets:
    - x
      layouts:




Pane
  name
  align left/right
  *Widget
  Theme

Widget
  depends: ... (sources)
  *Layout
  theme_selector

Layout
  alignment left/right/center
  width
  height
  markup
  markup_template

  newline true/false
  border ... color, radius, thickness
  background-color

Theme
  name
  colors (palette)
