# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action 
name: build
on: [push]
jobs:
  ubuntu-22_04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-ubuntu-22.04/
  archlinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-arch/
